<a href="https://colab.research.google.com/github/Mateo8911/data-sience-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# tekst

In [ ]:
### tekst

Wstęp, podstawy

In [2]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

In [ ]:
x=np.array([1,3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
y=np.array([1.3,2.3,1.4])
print(y)

[1.3 2.3 1.4]


In [ ]:
y.dtype

dtype('float64')

In [ ]:
z=np.array([[1,2], [-3,4]])
print(z)

[[ 1  2]
 [-3  4]]


In [ ]:
x=np.array([[1,2,4],[4,2,1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

In [ ]:
x=np.array(
    [[[4,3,1],
     [3,1,2]],

     [[4,1,3],
      [4,2,1]]]
    )
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

Typy Danych

In [ ]:
A=np.array([1,2,3],dtype='int')
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A=np.array([True,False])
A.dtype

dtype('bool')

In [ ]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype='int')

NameError: name 'shape' is not defined

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=101, step=10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
np.linspace(start=0, stop=1,num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
A = np.arange(15)

In [ ]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.reshape((-1,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
A=np.array([3,1,4,2])
B=np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [6]:
A+B

array([6, 0, 7, 4])

In [7]:
A-B

array([0, 2, 1, 0])

In [8]:
A+3

array([6, 4, 7, 5])

In [11]:
np.absolute(A)

array([3, 1, 4, 2])

In [12]:
A+3*B

array([12, -2, 13,  8])

In [13]:
np.add(A,B)

array([6, 0, 7, 4])

In [14]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [15]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [16]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [23]:
X=np.array([[1,3],[-2,0]])
Y=np.array([[6,0],[-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [24]:
X*Y

array([[6, 0],
       [2, 0]])

In [25]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [26]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [27]:
X@Y

array([[  3,   6],
       [-12,   0]])

In [28]:
np.random.seed(0)

In [30]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [31]:
np.random.randn(10,6)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433,
         1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982,  0.6536186 ,
         0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852, -0.18718385,
         1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647,
        -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275,
        -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218, -0.4380743 ,
        -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656,  0.3869025 ,
        -0.51080514],
       [-1.18063218, -0.02818223,  0.42833187,  0.06651722,  0.3024719 ,
        -0.63432209],
       [-0.36274117, -0.67246045, -0.35955316, -0.81314628, -1.7262826 ,
         0.17742614],
       [-0.40178094, -1.63019835,  0.46278226, -0.90729836,  0.0519454 ,
         0.72909056]])

In [32]:
np.random.rand()

0.31856895245132366

In [33]:
np.random.rand(10)

array([0.66741038, 0.13179786, 0.7163272 , 0.28940609, 0.18319136,
       0.58651293, 0.02010755, 0.82894003, 0.00469548, 0.67781654])

In [34]:
np.random.rand(10,5)

array([[0.27000797, 0.73519402, 0.96218855, 0.24875314, 0.57615733],
       [0.59204193, 0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782, 0.39650574],
       [0.8811032 , 0.58127287, 0.88173536, 0.69253159, 0.72525428],
       [0.50132438, 0.95608363, 0.6439902 , 0.42385505, 0.60639321],
       [0.0191932 , 0.30157482, 0.66017354, 0.29007761, 0.61801543],
       [0.4287687 , 0.13547406, 0.29828233, 0.56996491, 0.59087276],
       [0.57432525, 0.65320082, 0.65210327, 0.43141844, 0.8965466 ],
       [0.36756187, 0.43586493, 0.89192336, 0.80619399, 0.70388858],
       [0.10022689, 0.91948261, 0.7142413 , 0.99884701, 0.1494483 ]])

In [35]:
np.random.randint(10)

8

In [37]:
np.random.randint(low=10,high=101, size=10)

array([37, 93, 99, 33, 63, 61, 56, 30, 63, 39])

In [38]:
np.random.choice([4,2,1,3])

3

In [39]:
data = np.arange(10)
data


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.random.shuffle(data)

In [41]:
data

array([5, 0, 4, 2, 9, 6, 8, 1, 7, 3])

In [42]:
np.exp(1)

2.718281828459045

In [43]:
np.exp(2)

7.38905609893065

In [44]:
np.sqrt(9)

3.0

In [45]:
np.all([2,3,1])

True

In [48]:
np.all([1,0,3])

False

In [49]:
np.any([1,2,1])

True

In [50]:
np.any([0,0,0])

False

In [51]:
np.any([1,2,0])

True

In [54]:
A=np.random.rand(5)
print(A)

[0.23789282 0.934214   0.61396596 0.5356328  0.58990998]


In [55]:
np.argmax(A)

1

In [56]:
A[np.argmax(A)]

0.9342139979247938

In [57]:
np.argmin(A)

0

In [58]:
np.argsort(A)

array([0, 3, 4, 2, 1])

In [59]:
np.max(A)

0.9342139979247938

In [60]:
np.min(A)

0.23789282137450862

In [61]:
np.mean(A)

0.5823231109289455

In [62]:
np.median(A)

0.589909976354571

In [63]:
np.std(A)

0.22167464254373626

In [66]:
A=np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
A[2]

2

In [68]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [69]:
A[:2]

array([0, 1])

In [72]:
A[[0,2]]

array([0, 2])

In [73]:
A[10:15]

array([10, 11, 12, 13, 14])

In [83]:
B=A.reshape(4,5)


In [84]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
B[3]

array([15, 16, 17, 18, 19])

In [86]:
B[3,1]

16

In [87]:
B[:,3]

array([ 3,  8, 13, 18])

In [88]:
B[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [91]:
B[1,2]=14
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
for row in B:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [95]:
for row in B:
  print(row[2])

2
14
12
17


In [97]:
for row in B:
  print(row[0:2])

[0 1]
[5 6]
[10 11]
[15 16]


In [98]:
for item in B.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [99]:
B

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [100]:
B.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [101]:
B.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [108]:
C=np.arange(start=-10, stop=10, step=0.5)


array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [119]:
C=C.reshape(10,-1)


In [120]:
C > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [121]:
C[C>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [122]:
np.bitwise_and(C>-5,C<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [123]:
np.bitwise_or(C<-5,C>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])